apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: stacks
  name: stacks
spec:
  containers:
  - env:
    - name: TZ
      value: Europe/Oslo
    - name: server.context-path
      value: /stacks
    image: fintlabs.azurecr.io/stack-generator:latest
    name: stacks
    ports:
    - containerPort: 8080
    resources: {}
  restartPolicy: OnFailure
status: {}
