apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stacks
  name: stacks
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      io.kompose.service: stacks
  template:
    metadata:
      labels:
        io.kompose.service: stacks
    spec:
      restartPolicy: Always
      containers:
      - name: stacks
        image: fintlabs.azurecr.io/stack-generator:build.11
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 60
          timeoutSeconds: 5
          httpGet:
            port: 8080
            path: /stacks/health
        resources:
          limits:
            memory: "512Mi"
            cpu: "1"
        env:
        - name: TZ
          value: Europe/Oslo
        - name: JAVA_TOOL_OPTIONS
          value: "-XX:+ExitOnOutOfMemoryError -Xmx256m -verbose:gc"
        - name: server.context-path
          value: /stacks
