fint:
  admin:
    uri: https://admin-beta.fintlabs.no
  stack:
    type: Docker
  registry:
    username: jenkins
    password: password
    name: dtr.fintlabs.no/beta

server:
  context-path: /stacks
