fint:
  admin:
    uri: https://admin-beta.fintlabs.no
  stack:
    type: Docker
  registry:
    username: fintlabs
    password: password
    name: fintlabs.azurecr.io

server:
  context-path: /stacks
