apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.stack: administrasjon-kodeverk
    fint.role: consumer
  name: consumer-administrasjon-kodeverk
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    fint.stack: administrasjon-kodeverk
    fint.role: consumer
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    fint.stack: administrasjon-kodeverk
    fint.role: provider
  name: provider-administrasjon-kodeverk
spec:
  ports:
    - name: "8080"
      port: 8080
  type: LoadBalancer
  selector:
    fint.stack: administrasjon-kodeverk
    fint.role: provider
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fint.stack: administrasjon-kodeverk
    fint.role: consumer
  name: consumer-administrasjon-kodeverk
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      fint.stack: administrasjon-kodeverk
      fint.role: consumer
  template:
    metadata:
      labels:
        fint.stack: administrasjon-kodeverk
        fint.role: consumer
    spec:
      restartPolicy: Always
      containers:
        - name: consumer-administrasjon-kodeverk
          image: fintlabs.azurecr.io/consumer-administrasjon-kodeverk:3.2.1-3.1.0
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /administrasjon/kodeverk/health
          resources:
            limits:
              memory: "3Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "250m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError -XX:+UseG1GC -Xmx2G -verbose:gc"
            - name: fint.audit.mongo.databasename
              value: fint-audit-beta
            - name: fint.audit.mongo.connection-string
              valueFrom:
                secretKeyRef:
                  name: fint-audit
                  key: mongodb
            - name: fint.cache.manager
              value: default
            - name: fint.events.orgIds
              value: health.fintlabs.no
            - name: fint.hazelcast.kubernetes.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.namespace
              value: default
            - name: fint.hazelcast.kubernetes.labelName
              value: fint.stack
            - name: fint.hazelcast.kubernetes.labelValue
              value: administrasjon-kodeverk
            - name: fint.relations.default-base-url
              value: https://beta.felleskomponent.no
            - name: server.context-path
              value: /administrasjon/kodeverk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    fint.stack: administrasjon-kodeverk
    fint.role: provider
  name: provider-administrasjon-kodeverk
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      fint.stack: administrasjon-kodeverk
      fint.role: provider
  template:
    metadata:
      labels:
        fint.stack: administrasjon-kodeverk
        fint.role: provider
    spec:
      restartPolicy: Always
      containers:
        - name: provider-administrasjon-kodeverk
          image: fintlabs.azurecr.io/provider:PR-25.6
          ports:
            - containerPort: 8080
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 5
            httpGet:
              port: 8080
              path: /administrasjon/kodeverk/provider/health
          resources:
            limits:
              memory: "3Gi"
              cpu: "2"
            requests:
              memory: "2Gi"
              cpu: "250m"
          env:
            - name: TZ
              value: Europe/Oslo
            - name: JAVA_TOOL_OPTIONS
              value: "-XX:+ExitOnOutOfMemoryError -XX:+UseG1GC -Xmx2G -verbose:gc"
            - name: fint.audit.mongo.databasename
              value: fint-audit-beta
            - name: fint.audit.mongo.connection-string
              valueFrom:
                secretKeyRef:
                  name: fint-audit
                  key: mongodb
            - name: fint.events.orgIds
              value: health.fintlabs.no
            - name: fint.hazelcast.kubernetes.enabled
              value: "true"
            - name: fint.hazelcast.kubernetes.namespace
              value: default
            - name: fint.hazelcast.kubernetes.labelName
              value: fint.stack
            - name: fint.hazelcast.kubernetes.labelValue
              value: administrasjon-kodeverk
            - name: fint.provider.max-number-of-emitters
              value: "5"
            - name: server.context-path
              value: /administrasjon/kodeverk/provider
